name: Jesse Pascal JIT Compiler CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        sudo apt-get install  qemu-user-static binfmt-support gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user cmake build-essential -y --no-install-recommends &&
        sudo dpkg --add-architecture arm64
    - name: build
      run: |
        cmake -B build -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ && cmake --build build --parallel
    - name: link
      run: |
        sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /usr/lib/ld-linux-aarch64.so.1
    - name: test
      run: |
        python3 ./acceptance_test.py
      env:
        LD_LIBRARY_PATH: /usr/aarch64-linux-gnu/lib/

    
